### ISSUE TITLE
nearest neighbor bug: early termination an runs

### ISSUE THREAD

**Issue by yiorgb** [ChenhanYu/hmlp#33]
There is an if-block in the KNN code that is intended to terminate the KNN once the accuracy exceeds 80%.
There is a bug somewhere that causes `num_acc` to be zero, resulting in a division by zero, and the accuracy test always passes, and so it only does one iteration of KNN.
You can just comment out the if-block and the KNN search will run for n_tree iterations, which is 10 by default.
If that’s too much or too little, I would just hardcode whatever value you want for n_tree inside AllNearestNeighbor.
The code is in lines 1220-1225 of tree.hpp:
https://github.com/ChenhanYu/hmlp/blob/e8926d4d331c3a742c532157039db201d26b4c33/gofmm/tree.hpp#L1220-L1225.

**Comment by ChenhanYu** [comment]
Early termination has been removed in the following commit on the develop branch. We may add this feature back in the future while GOFMM is more robust. Close the issue.

commit e006446a840b0c0504bd70e93a613c1e973a7558
Author: Chenhan Yu <ych@login3.stampede2.tacc.utexas.edu>
Date:   Tue Jan 22 19:59:08 2019 -0600

    Now early termination in ANN has been disable.
