### ISSUE TITLE
Read large file in mpigofmm (out-of-core support)

### ISSUE THREAD

**Issue by Charles-Chao-Chen** [ChenhanYu/hmlp#40]
I am wondering if mpigofmm supports reading a large file that doesn't fit in the RAM. In the example, the SPDMatrix<T> class is not distributed:

https://github.com/ChenhanYu/hmlp/blob/master/example/test_mpigofmm.cpp#L72

Is there a distributed class for this functionality?

**Comment by ChenhanYu** [comment]
We provide a simple out-of-core (OOC) solution using mmap. 

See the following class in https://github.com/ChenhanYu/hmlp/blob/master/frame/containers/SPDMatrix.hpp

template<typename T>
class OOCSPDMatrix : public VirtualMatrix<T>

**Comment by Charles-Chao-Chen** [comment]
I replaced the SPDMatrix object with an OOCSPDMatrix object, but got the following error

/usr/local/bin/tacc_affinity: line 58: 59852 Bus error 

which didn't say much. So I'm wondering if it is a simple replacement with an OOCSPDMatrix object in test_mpigofmm.cpp

**Comment by ChenhanYu** [comment]
This looks about right. If the matrix size can fit into memory, mmap is nothing different then using malloc. The "real IO" only shows up when the requested size is actually larger than the memory size. Typically, you can implement a software cache to cache the values you have read, reusing them from the memory. We may already have a simple cache implementation. Let me take a look and get back to you.

**Comment by ChenhanYu** [comment]
I found that we actually have a simple software cache implemented in

https://github.com/ChenhanYu/hmlp/blob/master/frame/containers/Cache.hpp

There is an example of using the cache. See

https://github.com/ChenhanYu/hmlp/blob/master/frame/containers/PVFMMKernelMatrix.hpp

If you encounter any issue, let me know.

**Comment by Charles-Chao-Chen** [comment]
If I understand the example correctly, I need a wrapper over the original OOCSPDMatrix class and use Cache2D to cache entries that have been read, right?

**Comment by ChenhanYu** [comment]
That's right. The problem has been resolved. V2C.
